### ISSUE TITLE
IndexError: index out of range

### ISSUE THREAD

**Issue by F1NaL** [tsarpaul/FBUnpinner#13]
try to patch instagram v78
```
python3 patch.py libliger.so libliger-patched.so
```

```
[+] Patching TLS1.3 stack!
Traceback (most recent call last):
  File "patch.py", line 183, in <module>
    patcher13.patch()
  File "patch.py", line 118, in patch
    if blob[i+1] == 0b01000111 \
IndexError: index out of range
```

**Comment by F1NaL** [comment]
mistake with instagram version. On right version it work fine. Sorry
