### ISSUE TITLE
Fails when patching `libliger.so`

### ISSUE THREAD

**Issue by barissenkal** [tsarpaul/FBUnpinner#16]
```
[+] Patching TLS1.3 stack!
Traceback (most recent call last):
  File "patch.py", line 183, in <module>
    patcher13.patch()
  File "patch.py", line 118, in patch
    if blob[i+1] == 0b01000111 \
IndexError: index out of range
```

The `libliger.so` in question is released as over the air update between after 24 May, before 27 May.

**Comment by PATAPOsha** [comment]
Same with `libcoldstart.so` on Facebook 237.0.0.44.

**Comment by tsarpaul** [comment]
Try new version
